export const TASK1SELECTOR={
    "testIds": {
      "addFormButton": "add-form-button",
      "startFromScratchButton": "start-from-scratch-button",
      "addFullNameElement": "add-full-name-element",
      "fullNamePreviewGroup": "full-name-preview-group",
      "addPhoneNumberElement": "add-phone-number-element",
      "phonePreviewGroup": "phone-preview-group",
      "publishButton": "publish-button",
      "publishPreviewButton": "publish-preview-button",
      "phoneGroup": "phone-group",
      "fullNameGroup": "full-name-group",
      "emailGroup": "email-group",
      "startOrSubmitButton": "start-or-submit-button",
      "emailTextField": "email-text-field",
      "firstNameTextField": "first-name-text-field",
      "lastNameTextField": "last-name-text-field",
      "phoneNumberInputField": "phone-number-input-field",
      "thankYouPageContent": "thank-you-page-content",
      "submissionsTab": "submissions-tab",
      "neetoMoleculesMenuButton": "neeto-molecules-menu-button",
      "formDeleteButton": "form-delete-button",
      "deleteArchiveAlertArchiveCheckbox": "delete-archive-alert-archive-checkbox",
      "deleteArchiveAlertDeleteButton": "delete-archive-alert-delete-button",
      "contentTextField": "content-text-field",
      "addSingleChoiceElement": "add-single-choice-element",
      "singleChoiceOptionsContainer": "single-choice-options-container",
      "addMultiChoiceElement": "add-multi-choice-element",
      "multiChoiceOptionsContainer": "multi-choice-options-container",
      "addBulkOptionLink": "add-bulk-option-link",
      "bulkAddOptionsTextarea": "bulk-add-options-textarea",
      "bulkAddOptionsDoneButton": "bulk-add-options-done-button",
      "formSingleChoiceOption": "form-single-choice-option",
      "randomizeSwitchLabel": "randomize-switch-label",
      "singleChoiceOption": "single-choice-option",
      "formMultipleChoiceOption": "form-multiple-choice-option",
      "hideQuestionToggleLabel": "hide-question-toggle-label",
      "moreDropdownIcon": "more-dropdown-icon",
      "analyticsMoreTab": "analytics-more-tab",
      "visitsMetric": "visits-metric",
      "startsMetric": "starts-metric",
      "submissionsMetric": "submissions-metric",
      "completionRateMetric": "completion-rate-metric",
      "insightsCount": "insights-count",
      "addOptionLink":"add-option-link"
    },
    "urls": {
      "home": "/"
    },
    "timeouts": {
      "short": 1000,
      "medium": 3000,
      "long": 5000
    }
  }